name: osrm
description: Open Source Routing Machine (OSRM) client for Dart.
version: 0.0.5
repository: https://github.com/physia/kflutter/tree/main/osrm
homepage: https://github.com/physia/kflutter/tree/main/osrm
issue_tracker: https://github.com/flutter/flutter/issues?q=is:issue is:open label:"osrm"

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  async: ^2.11.0
  http: ^1.1.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

screenshots:
  - description: "Flutter Map With Directions (OSRM) example"
    path: images/screenshot_2023-08-02.png